apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeywell-webapp-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: {{ .Values.applabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.applabel }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

